%% Execute code section to build mex file for 64bit

clear; clc

mex('-IC:\Program Files\gtec\gUSBampCAPI\API\x64',...
	'-LC:\Program Files\gtec\gUSBampCAPI\API\x64',...
	'-I..\inc',...
	'-L..\lib',...
	'-lDAQgUSBAmp', '-lgUSBamp',...
	'DAQgUSBampMex.cpp');

%% Execute code section to build mex file for 32bit

clear; clc

mex( '-IC:\Program Files\gtec\gUSBampCAPI\API\Win32',...
	'-LC:\Program Files\gtec\gUSBampCAPI\API\Win32',...
	'-I..\inc',...
	'-L..\lib',...
	'-lDAQgUSBAmp', '-lgUSBamp',...
	'DAQgUSBampMex.cpp');
