function Hd = frontEndFilterBP(Fs)
%FRONTENDFILTERBP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 17-Oct-2016 10:42:19

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.

Fstop1 = 0.07;             % First Stopband Frequency
Fpass1 = 2.15;             % First Passband Frequency
Fpass2 = 40;               % Second Passband Frequency
Fstop2 = 44;               % Second Stopband Frequency
Dstop1 = 0.0039810717055;  % First Stopband Attenuation
Dpass  = 0.19879359342;    % Passband Ripple
Dstop2 = 0.0039810717055;  % Second Stopband Attenuation
dens   = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
